### ISSUE TITLE
Setup React Router & create container & form components for Home, Login, and Register

### ISSUE THREAD

**Issue by noi5e** [chingu-voyages/doggo-playdate-tinder#2]
As a user, I can create a profile upon registering by entering my:
- name
- dog's name
- age
- location
- brief description of dog
- ~doggy profile picture~ (handled in a separate issue in this repo)

**Comment by destiny-ross-dev** [comment]
It isn't clear what the intent of this issue is. Are you suggesting that profile creation should happen _during_ the user registration process? I think it should be separate, as part of onboarding. 
<img width="624" alt="Screen Shot 2019-11-14 at 9 34 12 PM" src="https://user-images.githubusercontent.com/44125370/68912595-93520880-0726-11ea-9b71-abb05ea53d9a.png">

**Comment by noi5e** [comment]
The flow you mentioned makes sense to me. I made these initial issues quickly without thinking too much about the details, I figured we would discuss things as they came up as we're doing now.

Like I mentioned in another issue, I think we should consider how people enter their city and state, and find a way to validate/standardize the input so we can group users by city.

Other unrelated note: I wonder if a dropdown field for the dog breed is the best format. There's a lot of dog breeds after all, and lots of dogs are mutts. People might want to select more than one breed for their dog. If we do end up implementing that as a feature.
